### ISSUE TITLE
python errors while running moudles.

### ISSUE THREAD

**Issue by Bishalkaucha** [DataSploit/datasploit#133] opened 2017-07-05 14:41 UTC
I got these types of errors while running various modules like emaiOsint and usernameOsint. 

---> Finding Paste(s)

Traceback (most recent call last):
  File "emailOsint.py", line 13, in <module>
    run(email)
  File "emailOsint.py", line 8, in run
    osint_runner.run("email", "emails", email)
  File "/root/Desktop/Pentest/datasploit/osint_runner.py", line 23, in run
    data = x.main(m_input)
  File "/root/Desktop/Pentest/datasploit/emails/email_pastes.py", line 61, in main
    data = google_search(email)
  File "/root/Desktop/Pentest/datasploit/emails/email_pastes.py", line 44, in google_search
    if int(data['searchInformation']['totalResults']) > 0:
KeyError: 'searchInformation'

**Comment by KunalAggarwal** [comment] 2017-07-06 18:23
I've seen this happen when using Google Search API frequently. Looks like a throttling from Google.
Thank you for pointing out, will incorporate it's error handling in the next release.

**Comment by spmedia** [comment] 2017-07-07 19:58
I'm getting this same error. It has never been able to fully run.

Command I'm using: python domainOsint.py example.com

It happens when I get to the "**---> Finding Paste(s)..**" section

Traceback (most recent call last):
  File "domainOsint.py", line 13, in <module>
    run(domain)
  File "domainOsint.py", line 8, in run
    osint_runner.run("domain", "domain", domain)
  File "/root/datasploit-1.0/osint_runner.py", line 23, in run
    data = x.main(m_input)
  File "/root/datasploit-1.0/domain/domain_pastes.py", line 62, in main
    data = google_search(domain)
  File "/root/datasploit-1.0/domain/domain_pastes.py", line 44, in google_search
    if int(data['searchInformation']['totalResults']) > 0:
KeyError: 'searchInformation'

**Comment by Plazmaz** [comment] 2017-07-13 17:06
Looks to be a regression of #90

**Comment by KunalAggarwal** [comment] 2017-11-11 10:42
This was fixed in some previous commit and additional handling was added c2b10083c6a7a865e914d04e10225a57b9b2c78

**Closed as completed by KunalAggarwal** 2017-11-11 10:42 UTC
