### ISSUE TITLE
Add Subbrute

### ISSUE THREAD

**Issue by menzow** [DataSploit/datasploit#43] opened 2016-08-16 11:22 UTC
I think implementing (subbrute)[https://github.com/TheRook/subbrute] would be a nice addition for scanning DNS entries.

More info: https://www.youtube.com/watch?v=ekUQIVUzDX4

Anyone agree?

**Comment by upgoingstar** [comment] 2016-08-17 21:03
Hi, I agree with your views. Adding subbrute could be helpful, but I see two problems with it. 
1. It hits the server, i.e. server gets a log, which we do not want. 
2. Brute forcing subdomains with patterns like x.y.z.abc.com becomes almost impossible. 

Having said that, I do not underestimate the importance of it. We can probably write down a module for this, but not sure if this should be included in automated part or not. 

Please suggest your views for including in automated part?

**Comment by SudhanshuC** [comment] 2016-08-18 06:48
What we can do is create a dictionary of some common sub-domains and ask the user explicitly if they want to include this for discovery. Of course users can modify the dictionary as per requirement.

**Comment by upgoingstar** [comment] 2016-11-16 12:33
@SudhanshuC / @nkpanda would you guys like to pick this up?

**Comment by upgoingstar** [comment] 2017-04-01 00:07
Not including subbrute, but will add few more sources into datasploit 

hence it goes as Duplicate of #113

**Closed as completed by upgoingstar** 2017-04-01 00:07 UTC
Labels: enhancement
